definitions:
  entity.User:
    properties:
      creation_timestamp:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      update_timestamp:
        type: string
      username:
        type: string
    type: object
  request.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is the Vision Backend API.
  title: Vision Backend API
  version: v0.1.0
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Create a new user
      operationId: createUser
      parameters:
      - description: Created user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "429":
          description: Too Many Requests
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create user
      tags:
      - user
swagger: "2.0"
